# Generated by Django 5.0.6 on 2024-07-02 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_review_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='url',
        ),
    ]
